// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi4CUiRhxrNF93_cgPpWKWgIRLAkkIIhQ',
    appId: '1:239637526998:web:d9f2d9bfc9c4159148cc77',
    messagingSenderId: '239637526998',
    projectId: 'mp-lab-ese-2fea2',
    authDomain: 'mp-lab-ese-2fea2.firebaseapp.com',
    storageBucket: 'mp-lab-ese-2fea2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPX3N2sJkHsCQT2AXkqvNbLVFvIjZ-gA',
    appId: '1:239637526998:android:f0d85f7a3033610448cc77',
    messagingSenderId: '239637526998',
    projectId: 'mp-lab-ese-2fea2',
    storageBucket: 'mp-lab-ese-2fea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbdx5JuzKdHrxbLCeljL5Wqb_arSa3LV8',
    appId: '1:239637526998:ios:d2d124a83acbedcb48cc77',
    messagingSenderId: '239637526998',
    projectId: 'mp-lab-ese-2fea2',
    storageBucket: 'mp-lab-ese-2fea2.firebasestorage.app',
    iosBundleId: 'com.example.labEse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbdx5JuzKdHrxbLCeljL5Wqb_arSa3LV8',
    appId: '1:239637526998:ios:d2d124a83acbedcb48cc77',
    messagingSenderId: '239637526998',
    projectId: 'mp-lab-ese-2fea2',
    storageBucket: 'mp-lab-ese-2fea2.firebasestorage.app',
    iosBundleId: 'com.example.labEse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi4CUiRhxrNF93_cgPpWKWgIRLAkkIIhQ',
    appId: '1:239637526998:web:2ac0604cdcbdcc6d48cc77',
    messagingSenderId: '239637526998',
    projectId: 'mp-lab-ese-2fea2',
    authDomain: 'mp-lab-ese-2fea2.firebaseapp.com',
    storageBucket: 'mp-lab-ese-2fea2.firebasestorage.app',
  );
}
