// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHrWknp8t4NuiD6qT8Oa06kV9ZyeJGV8s',
    appId: '1:1035803595604:web:8948696c77deed247aaec1',
    messagingSenderId: '1035803595604',
    projectId: 'mca-lab-8-firebase',
    authDomain: 'mca-lab-8-firebase.firebaseapp.com',
    storageBucket: 'mca-lab-8-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcT87_zxwDLhetZUvV9RtSGBJVvPs6GC8',
    appId: '1:1035803595604:android:434cc8b927d5083f7aaec1',
    messagingSenderId: '1035803595604',
    projectId: 'mca-lab-8-firebase',
    storageBucket: 'mca-lab-8-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPu55L-j6fB8orZFKt2ByFMVohxSxJDaY',
    appId: '1:1035803595604:ios:a2f906d528a3abae7aaec1',
    messagingSenderId: '1035803595604',
    projectId: 'mca-lab-8-firebase',
    storageBucket: 'mca-lab-8-firebase.firebasestorage.app',
    iosBundleId: 'com.example.lab8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPu55L-j6fB8orZFKt2ByFMVohxSxJDaY',
    appId: '1:1035803595604:ios:a2f906d528a3abae7aaec1',
    messagingSenderId: '1035803595604',
    projectId: 'mca-lab-8-firebase',
    storageBucket: 'mca-lab-8-firebase.firebasestorage.app',
    iosBundleId: 'com.example.lab8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHrWknp8t4NuiD6qT8Oa06kV9ZyeJGV8s',
    appId: '1:1035803595604:web:a47c7757fff7d2607aaec1',
    messagingSenderId: '1035803595604',
    projectId: 'mca-lab-8-firebase',
    authDomain: 'mca-lab-8-firebase.firebaseapp.com',
    storageBucket: 'mca-lab-8-firebase.firebasestorage.app',
  );
}
